import os
import subprocess
import tempfile
import logging

# Configure basic logging
logging.basicConfig(level=logging.INFO, format='[%(levelname)s] %(message)s')

def get_xfoil_executable():
    """
    Finds the XFOIL executable.
    Assumes 'xfoil.exe' on Windows or 'xfoil' on Linux/WSL are in the project root.
    """
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir) # Go up one level from naca_aero_suite
    
    if os.name == 'nt':
        return os.path.join(project_root, "xfoil.exe")
    else:
        # Assumes 'xfoil' is in the PATH or in the project root for Linux/WSL
        local_xfoil = os.path.join(project_root, "xfoil")
        if os.path.exists(local_xfoil):
            return local_xfoil
        return "xfoil"

class XFoilAnalysis:
    """A wrapper for running an XFOIL analysis."""

    def __init__(self, airfoil_name="airfoil", alpha=0.0, reynolds=1e6, mach=0.0, ncrit=9.0):
        self.airfoil_name = airfoil_name
        self.alpha = alpha
        self.reynolds = reynolds
        self.mach = mach
        self.ncrit = ncrit
        self.xfoil_exe = get_xfoil_executable()

    def run_analysis(self, X, Y):
        """
        Runs an XFOIL analysis for a given airfoil geometry.

        Args:
            X (np.ndarray): X-coordinates of the airfoil.
            Y (np.ndarray): Y-coordinates of the airfoil.

        Returns:
            tuple: A tuple containing (Cl, Cd, achieved_alpha). Returns (None, None, None) on failure.
        """
        if not os.path.exists(self.xfoil_exe):
            logging.error(f"XFOIL executable not found at '{self.xfoil_exe}'. Aborting analysis.")
            return None, None, None
            
        with tempfile.TemporaryDirectory() as temp_dir:
            airfoil_file = os.path.join(temp_dir, f"{self.airfoil_name}.dat")
            polar_file = os.path.join(temp_dir, "polar.dat")
            xfoil_input_file = os.path.join(temp_dir, "xfoil_input.in")

            # Save airfoil to file
            with open(airfoil_file, "w") as f:
                for i in range(len(X)):
                    f.write(f"{X[i]:.6f} {Y[i]:.6f}
")

            # Create XFOIL input file
            self._create_xfoil_input(airfoil_file, polar_file)

            # Run XFOIL
            try:
                with open(xfoil_input_file, "r") as stdin_file:
                    subprocess.run(
                        [self.xfoil_exe],
                        stdin=stdin_file,
                        capture_output=True,
                        text=True,
                        timeout=30,
                        cwd=temp_dir
                    )
            except FileNotFoundError:
                logging.error(f"XFOIL executable not found at '{self.xfoil_exe}'. Ensure it is in the correct path.")
                return None, None, None
            except subprocess.TimeoutExpired:
                logging.warning("XFOIL process timed out. Airfoil may not have converged.")
                return None, None, None
            except Exception as e:
                logging.error(f"An unexpected error occurred while running XFOIL: {e}")
                return None, None, None

            # Parse polar results
            return self._parse_polar_file(polar_file)

    def _create_xfoil_input(self, airfoil_file, polar_file):
        """Generates the XFOIL command script."""
        input_filename = os.path.basename(airfoil_file)
        
        with open(os.path.join(os.path.dirname(airfoil_file), "xfoil_input.in"), "w") as f:
            f.write(f"LOAD {input_filename}
")
            f.write("PANE
OPER
")
            f.write(f"Visc {self.reynolds}
")
            f.write(f"Mach {self.mach}
")
            f.write("VPAR
")
            f.write(f"N {self.ncrit}

")
            f.write("ITER 500
")
            f.write("PACC
")
            f.write(f"{polar_file}

") # Use a clean polar file
            
            # Sequence of angles to approach the target alpha
            if self.alpha == 0.0:
                f.write("ALFA 0.0
")
            else:
                # Approach target alpha with a small step to aid convergence
                step = 1.0 if self.alpha > 0 else -1.0
                safe_end = self.alpha - step / 2
                if abs(safe_end) > 0.01:
                    f.write(f"ASEQ 0.0 {safe_end} {step}
")
                f.write(f"ALFA {self.alpha}
")
            f.write("
QUIT
")

    def _parse_polar_file(self, polar_file):
        """Parses the polar file generated by XFOIL to find the data for the target alpha."""
        cl, cd, achieved_alpha = None, None, None
        try:
            with open(polar_file, "r") as f:
                # Read lines, skipping header
                lines = [line for line in f if not line.strip().startswith("#") and len(line.strip()) > 0]
                if not lines:
                    return None, None, None

                best_diff = float('inf')
                for line in lines:
                    try:
                        data = line.split()
                        if len(data) >= 3:
                            a_val, cl_val, cd_val = float(data[0]), float(data[1]), float(data[2])
                            diff = abs(a_val - self.alpha)
                            if diff < best_diff:
                                best_diff = diff
                                achieved_alpha, cl, cd = a_val, cl_val, cd_val
                    except (ValueError, IndexError):
                        continue # Skip malformed lines
        except IOError:
            logging.warning(f"Could not read XFOIL polar file: {polar_file}")

        return cl, cd, achieved_alpha

